- name: clone some repos
  git: repo="{{ item.url }}" dest="{{ item.dest }}" accept_hostkey="yes" update="no"
  become: true
  become_user: "{{ user }}"
  with_items:
    - { "url": "git@gitlab.com:arecker/blog.git", "dest": "~/src/blog" }
    - { "url": "git@gitlab.com:arecker/notes.git", "dest": "~/src/notes" }
