---
- hosts: local
  roles:
    - base

  tasks:
    - name: add emacs ppa
      apt_repository: repo="ppa:kelleyk/emacs"
      become: true
    - name: install package
      package: name="emacs26" state="present"
      become: true
    - name: install java, sure
      package: name="default-jre" state="present"
      become: true
