---
- hosts: local
  roles:
    - base

  tasks:
    - name: fix default keyboard
      lineinfile: name="/etc/default/keyboard" regexp="^XKBOPTIONS" line="XKBOPTIONS=\"ctrl:nocaps\""
      become: true

    - name: clone emacs source
      git: repo="git://git.sv.gnu.org/emacs.git" dest="~/src/emacs" update="no"

    - name: install emacs dependencies
      package: name="{{ item }}" state="present"
      become: true
      with_items:
        - autoconf
        - automake
        - libtool
        - texinfo
        - build-essential
        - xorg-dev
        - libgtk2.0-dev
        - libjpeg-dev
        - libncurses5-dev
        - libdbus-1-dev
        - libgif-dev
        - libtiff-dev
        - libm17n-dev
        - libpng-dev
        - librsvg2-dev
        - libotf-dev
        - libgnutls28-dev
        - libxml2-dev

    - name: install xorg
      package: name="xorg" state="present"
      become: true

    - name: install i3-gaps dependencies
      package: name="{{ item }}" state="present"
      become: true
      with_items:
        - libxcb-keysyms1-dev
        - libpango1.0-dev
        - libxcb-util0-dev
        - xcb
        - libxcb1-dev
        - libxcb-icccm4-dev
        - libyajl-dev
        - libev-dev
        - libxcb-xkb-dev
        - libxcb-cursor-dev
        - libxkbcommon-dev
        - libxcb-xinerama0-dev
        - libxkbcommon-x11-dev
        - libstartup-notification0-dev
        - libxcb-randr0-dev
        - libxcb-xrm0
        - libxcb-xrm-dev

    - name: install inconsolata
      package: name="fonts-inconsolata" state="present"
      become: true

    - name: motd
      copy: src="files/motd" dest="/etc/motd"
      become: true

    - name: dirs
      copy: src="files/user-dirs.dirs" dest="~/.config/user-dirs.dirs"

    - name: install random packages
      package: name="{{ item }}" state="present"
      become: true
      with_items:
        - xscreensaver
        - xscreensaver-data
        - xscreensaver-data-extra
        - xscreensaver-gl
        - xscreensaver-gl-extra
        - xscreensaver-screensaver-bsod

    - name: link xinitrc
      file: src="{{ playbook_dir }}/files/xinitrc" dest="~/.xinitrc" state="hard" force="yes"

    - name: link xresources
      file: src="{{ playbook_dir }}/files/xresources" dest="~/.Xresources" state="hard" force="yes"
