---
- hosts: local
  roles:
    - base

  tasks:
    - name: fix default keyboard
      lineinfile: name="/etc/default/keyboard" regexp="^XKBOPTIONS" line="XKBOPTIONS=\"ctrl:nocaps\""
      become: true

    - name: clone emacs source
      git: repo="git://git.sv.gnu.org/emacs.git" dest="~/src/emacs" update="no"

    - name: install emacs dependencies
      package: name="{{ item }}" state="present"
      become: true
      with_items:
        - autoconf
        - automake
        - libtool
        - texinfo
        - build-essential
        - xorg-dev
        - libgtk2.0-dev
        - libjpeg-dev
        - libncurses5-dev
        - libdbus-1-dev
        - libgif-dev
        - libtiff-dev
        - libm17n-dev
        - libpng-dev
        - librsvg2-dev
        - libotf-dev
        - libgnutls28-dev
        - libxml2-dev

    - name: install inconsolata
      package: name="fonts-inconsolata" state="present"
      become: true

    - name: motd
      copy: src="files/motd" dest="/etc/motd"
      become: true

    - name: dirs
      copy: src="files/user-dirs.dirs" dest="~/.config/user-dirs.dirs"

    - name: screensaver
      package: name="{{ item }}" state="present"
      become: true
      with_items:
        - xscreensaver
        - xscreensaver-data
        - xscreensaver-data-extra
        - xscreensaver-gl
        - xscreensaver-gl-extra
        - xscreensaver-screensaver-bsod

    - name: install java, sure
      package: name="openjdk-9-jre-headless" state="present"
      become: true
