---
- name: installing dependencies
  package: name="{{ item }}" state="present"
  become: true
  with_items:
  - build-essential
  - curl
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - llvm
  - make
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev
- name: link bootstrap script
  file: src="{{ playbook_dir }}/roles/python/files/pyenv-bootstrap.sh" dest="~/bin/pyenv-bootstrap.sh" state="hard"
  become: true
  become_user: "{{ user }}"
