- name: install package
  package: name="openssh-client" state="present"
  become: true
- block:
  - name: make config directory
    file: path="~/.ssh" state="directory" mode="700"
  - name: copy keys
    copy: src="files/{{ item }}" dest="~/.ssh/{{ item }}" mode="400"
    with_items: [ id_rsa, id_rsa.pub ]
  - name: copy config
    copy: src="files/config" dest="~/.ssh/config" mode="600"
  become: true
  become_user: "{{ user }}"
