- name: install dependencies
  package: name="{{ item }}" state="present"
  become: true
  with_items:
    - autoconf
    - automake
    - build-essential
    - libdbus-1-dev
    - libgif-dev
    - libgnutls28-dev
    - libgtk2.0-dev
    - libjpeg-dev
    - libm17n-dev
    - libncurses5-dev
    - libotf-dev
    - libpng-dev
    - librsvg2-dev
    - libtiff-dev
    - libtool
    - libxml2-dev
    - texinfo
    - xorg-dev
- name: link emacs-build.sh
  file: src="{{ playbook_dir }}/roles/emacs-build/files/emacs-build.sh" dest="~/bin/emacs-build.sh" state="hard"
  become: true
  become_user: "{{ user }}"
- name: clone emacs source
  git: repo="git://git.sv.gnu.org/emacs.git" dest="~/src/emacs" update="no"
  become: true
  become_user: "{{ user }}"
