- name: copy ssh keys
  copy: src="files/{{ item }}" dest="~/.ssh/{{ item }}" mode="400"
  with_items: [ id_rsa, id_rsa.pub ]

- name: install git
  package: name="git" state="present"
  become: "{{ can_sudo }}"

- name: install pass
  package: name="pass" state="present"
  become: "{{ can_sudo }}"
- name: clone password store
  git: repo="ssh://git@gitlab.com/arecker/password-store" dest="~/.password-store" accept_hostkey="yes" key_file="~/.ssh/id_rsa" update="no"

- name: install pyenv dependencies
  package: name="{{ item }}" state="present"
  become: true
  when: ansible_distribution != 'MacOSX'
  with_items:
  - build-essential
  - curl
  - git
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - llvm
  - make
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev

- name: install rbenv dependencies
  package: name="{{ item }}" state="present"
  when: ansible_distribution != 'MacOSX'
  become: true
  with_items:
    - autoconf
    - bison
    - build-essential
    - git
    - libffi-dev
    - libgdbm-dev
    - libgdm-dev
    - libncurses5-dev
    - libreadline6-dev
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
- name: install rbenv
  git: repo="https://github.com/rbenv/rbenv.git" dest="~/.rbenv" update="no" depth="1"

- name: install sbcl
  package: name="sbcl" state="present"
  become: "{{ can_sudo }}"
- name: bootstrap quicklisp
  command: "{{ playbook_dir }}/roles/base/files/bootstrap-quicklisp.sh"
  args:
    creates: ~/.quicklisp

- name: install nodenv
  git: repo="https://github.com/nodenv/nodenv.git" dest="~/.nodenv" update="no" depth="1"
- name: make nodenv plugins directory
  file: path="~/.nodenv/plugins" state="directory" mode="751"
- name: install nodenv plugins
  git: repo="https://github.com/nodenv/{{ item }}.git" dest="~/.nodenv/plugins/{{ item }}" update="no" depth="1"
  with_items:
    - node-build
