- name: install package
  package: name="gnupg" state="present"
  become: true
- block:
  - name: check if gnupg folder exists
    stat: path="~/.gnupg"
    register: gnupg_dir
  - name: create import directory
    file: path="~/gpg_import" state="directory"
    when: not gnupg_dir.stat.exists
  - name: copy keys
    copy: src="files/{{ item }}" dest="~/gpg_import/{{ item }}"
    with_items: [ public.gpg.asc, private.gpg.asc ]
    when: not gnupg_dir.stat.exists
  - name: import keys
    command: gpg --import "/home/{{ user }}/gpg_import/{{ item }}"
    with_items: [ public.gpg.asc, private.gpg.asc ]
    when: not gnupg_dir.stat.exists
  - name: delete import directory
    file: path="~/gpg_import" state="absent"
  become: true
  become_user: "{{ user }}"
