- name: install dependencies
  package: name="{{ item }}" state="present"
  become: true
  with_items:
    - autoconf
    - bison
    - build-essential
    - libffi-dev
    - libgdbm-dev
    # - libgdbm3
    - libncurses5-dev
    - libreadline6-dev
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev
- name: render gem config
  template: src="templates/gemrc.j2" dest="~/.gemrc" mode="644"
  become: true
  become_user: "{{ user }}"
- name: link rbenv-bootstrap.sh
  file: src="{{ playbook_dir }}/roles/ruby/files/rbenv-bootstrap.sh" dest="~/bin/rbenv-bootstrap.sh" state="hard"
  become: true
  become_user: "{{ user }}"
